name: Build

on:
  push:
    branches:
    - develop
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  CONFIGURATION: 'Debug'
  VERBOSITY:  'Normal'

jobs: 
  Build:
    name: Build TinyCLR    
    runs-on: [windows-latest]
    strategy:
      matrix:
        vs-version: [16.6]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract build information into variables
      id: info
      run: |
        echo "##[set-output name=build;]$(echo $(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo Â© $(date -u +%Y) Bytewizer.  All rights reserved.)"

    - name: Show build information
      run: |
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: ${{ matrix.vs-version }}       
    
    - name: Restore project
      working-directory: src
      run: >- 
        msbuild -t:restore -verbosity:${env:VERBOSITY} 

    - name: Build and pack libraries
      working-directory: src
      run: >- 
        msbuild -t:pack -verbosity:${env:VERBOSITY} 
        -p:PackageOutputPath=\builds\artifacts
        -p:BuildNumber="${{ steps.info.outputs.build }}" 
        -p:Copyright="${{ steps.info.outputs.copyright }}"
        -p:VersionSuffix=prebuild.${{ steps.info.outputs.build }} 
        -p:Configuration=${env:CONFIGURATION}
        -p:RepositoryUrl="https://github.com/microcompiler/microserver"
        -p:PackageTags="tcp-server udp-server socket-server http-server http https tinyclr tinyclros sitcore iot"
        -p:IncludeSymbols=true 
        -p:SymbolPackageFormat="snupkg"
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
            
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Build Package
        path: \builds\artifacts
